title: Tomas Lukavec - Academic
description: > # this means to ignore newlines until "baseurl:"
  Personal website and academic blog focusion on social research.
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tomas Lukavec # add your name
author-img: fotka.jpg # add your photo
about-author: Ph.D. Candidate in Public Policy, currently visiting scholar at the University of Colorado, Denver. # add description
social-twitter: TomLuk739 # add your Twitter handle
social-instagram: tom.lukavec # add your Facebook handle
social-linkedin: # add your Linkedin handle
social-email: test@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
